### ISSUE TITLE
observed "lx_cgroup: [ID 894024 kern.warning] WARNING: cgrp: event queue full for zone" on 20160317 along with process slowness

### ISSUE THREAD

**Issue by ingenthr** [joyent/illumos-joyent#101]
I've just updated to 20160317 and set up a new lx brand zone.  Even at initial boot, the log is showing…
```
lx_cgroup: [ID 894024 kern.warning] WARNING: cgrp: event queue full for zone 6cbb043f-4437-e86b-b0be-c6f3dff164fc
```

This seemed to correlate with some slowness with a mainly IO driven task (a "yum install" on the lx brand in question).  

Poking around a bit further, it looks like this means "something is wrong" per [a comment I found in the code](https://github.com/joyent/illumos-joyent/blob/73f5cc942453127cb4938757278373c37300a0c6/usr/src/uts/common/brand/lx/cgroups/cgrps_vfsops.c#L920-L928)

It comes up pretty frequently:
```
# dmesg | grep "event queue full" | wc -l
      45
```

Since this appears to be filesystem IO related, the underlying system has two physical disks along with a single SSD front-ending it as both a cache and log device (two slices).  IO wise, it's performed well.

```
# zpool status -v
  pool: zones
 state: ONLINE
status: Some supported features are not enabled on the pool. The pool can
	still be used, but some features are unavailable.
action: Enable all features using 'zpool upgrade'. Once this is done,
	the pool may no longer be accessible by software that does not support
	the features. See zpool-features(5) for details.
  scan: resilvered 235G in 2h45m with 0 errors on Tue Mar 31 03:49:12 2015
config:

	NAME        STATE     READ WRITE CKSUM
	zones       ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    c1t0d0  ONLINE       0     0     0
	    c1t1d0  ONLINE       0     0     0
	logs
	  c0t1d0s0  ONLINE       0     0     0
	cache
	  c0t1d0s1  ONLINE       0     0     0

errors: No known data errors
```

Is there any additional data I can gather?

**Comment by jjelinek** [comment]
The lx cgroup implementation currently uses a user-level daemon to run the release agent for a cgroup mountpoint. The message you are seeing usually means that the daemon is no longer running (which is why the event queue filled up). You can check that by running ps in the zone and looking for cgrpmgr. It is likely that something has inadvertently killed the daemon. What image are you running? I'll see if I can reproduce this and figure out if it's a generic problem with the image, or due to something else.

**Comment by jjelinek** [comment]
This was fixed with OS-4825.

**Comment by ingenthr** [comment]
Thanks much for the fix!  Apologies for not replying to the request about which image it was.  I'll look to verify it when it's in a build and will let you know if I still see it.
